### Site metadata ###

site_name: YFPY - Yahoo Fantasy Sports API Wrapper
site_description: Python API wrapper for the Yahoo Fantasy Sports public API
site_url: https://yfpy.uberfastman.com
site_author: "Wren J. R. (uberfastman)"

repo_url: https://github.com/uberfastman/yfpy
edit_uri: ""

### Build settings ###

extra:
  version: !ENV [YFPY_VERSION, 'vX.X.X']

docs_dir: docs-mkdocs
site_dir: docs

theme:
#  name: mkdocs
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 6
  logo: yfpy-logo.svg

extra_css:
  - extra.css

extra_javascript:
  - extra.js

nav:
  - Welcome: index.md
  - YFPY - Yahoo Fantasy Sports API Wrapper: readme.md
  - Example Usage:
    - Quickstart: quickstart.md
  - Package:
    - Query: query.md
    - Data: data.md
    - Models: models.md
  - Extras:
    - Utilities: utils.md
    - Exceptions: exceptions.md
    - Logging: logger.md
  - Testing:
    - PyTest: test.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
  - sane_lists
  - codehilite

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
#      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            separate_signature: true
            show_submodules: true
            docstring_section_style: table
            members_order: source
            summary: true
