# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version to ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.17"
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --dev
        source .venv/bin/activate

    - name: Lint with ruff
      run: |
        source .venv/bin/activate
        ruff check .

    - name: Security check with bandit
      run: |
        source .venv/bin/activate
        bandit -c pyproject.toml -r .

#    - name: Run tests with pytest
#      working-directory: ./
#      run: make test_code
